6,6,0,100,5,0,0
"BEWARE OF RATS"
"@"
"@"
"@"
"@"
"@"
"*** PER ASPERA AD ASTRA ***"
"@"
"@"
"NORTH EAST TOWER"
0
1
1
1
1
-1
1
3
1
1
0
1
1
1
1
-4
1
0
0
1
0
0
1
0
1
0
0
1
0
1
-5
0
0
1
1
0
1
1
1
1
85
66
7
0he functions of NSWP have now been described.  The best way to  get 
more familiar with the program is to actually USE it.  I think it will be 
one of your most frequently used programs.

There are several things in this version that you will want to a
3
62
0
0
0
1
0
0
1
1
0
0
1
0
0
1
0
0
0
1
1
0
1
0
1
0
0
1
1
1
1
0
15
0
1
7
0
1
0
1
0
0
1
0
0
1
-7
0
1
1
0
-6
1
1
0
0
0
0
1
1
0
0
1
1
1
1
0
1
0
1
0
0
1
0
1
0
0
1
1
0
0
-8
0
lter:


103H

This  byte controls the screen length used in the 'V'iew command.  It  is 
currently set to 23D (17H).


104H-10AH - Turn reverse video on

The  first byte in this sequence of seven shows the length of the reverse 
video on sequen