6,6,0,100,5,0,0
"PTHERODACTILI"
"@"
"@"
"@"
"@"
"@"
"I can only promise you toil, tears, sweat and blood,"
"But the coward dies many times before he perishes"
"@"
"NE TOWER FLOOR 1"
0
1
2
0
1
0
0
1
0
1
0
0
0
0
1
0
0
1
0
1
0


Drive B*: 950K in 234 files. 2956K free.

From this point, you may execute any of the menu options.

A special display occurs if no files are found with the specification you 
have given, or if there are no files in the given drive/user area(s):
0
0
0
1
0
0
1
0
1
0
0
0
1
1
0
66
2
0
2
-2
0
1
1
1
0
1
0
1
0
0
1
1
1
1
0
1
0
1
0
0
1
1
1
1
0
1
0
1
0
0
1
0
0
2
0
0
1
0
1
-6
0
0
0
0
0
0
1
0
1
-3
0
0
0
0
0
0
1
0
1
0
0
0
1
0

No files.

This  display  may also occur if you delete all the files out of a  given 
specification.  When this occurs,  your menu choices are limited to  ONLY 
'S', 'L' or 'X'. This allows you to see the free Space on a drive, to Log 
to another dri0
1
0
1
0
0
1
1
1
1
0
1
0
1
0
0
1
1
1
1
0
1
0
1
0
0
1
1
1
1
0
1
0
1
0
0
1
0
0
0
0
0
1