6,6,0,100,3,0,0
"PTHERODACTILI"
"@"
"@"
"@"
"@"
"@"
"@"
"@"
"@"
"NORTH WEST TOWER"
0
1
0
1
1
0
1
1
1
1
0
1
0
0
1
-5
0
1
0
1
0
0
0
1
1
0
1
1
1
1
0
1
1
1
1
-8
1
0
1
0
-2
1
1
0
1
0
0
1
1
0
0
1
1
invoked NSWP from,  regardless  of 
anything you may have done in NSWP.

Finding a file

Since you may have many hundreds of files selected,  you may wish to move 
rapidly  to a particular file.  You may do this through the 'F',  or FIND 
command.
1
1
0
1
0
0
0
0
0
1
0
1
0
0
0
1
1
0
1
0
1
0
-4
1
0
0
1
0
0
1
0
1
0
0
1
0
1
0
0
1
1
0
0
1
2
1
1
0
1
0
1
0
0
1
0
1
0
0
1
1
0
0
0
0
1
0
1
0
0
1
0
1
0
0
1
0
1
0
0
0
1
2
-9
1
0
  1. B0: -WORK   .001   0K : F Which file? BASCOM
 
  8. B0: BASCOM  .COM  32K : 

The Find command always starts looking from entry number one. You may use 
the  standard  CP/M syntax for wildcarding (eg:  to find the  first  .HEX 
file,  you may 