# SPDX-FileCopyrightText: 2026 P2000C SASI Distribution contributors
# SPDX-License-Identifier: GPL-3.0-or-later

"""Known geometry and observed layout of P2000C hard-drive images."""

IMAGE_SIZE = 10_485_760
SECTOR_SIZE = 256
SECTOR_COUNT = 40_960

SYSTEM_AREA_START_LBA = 0
SYSTEM_AREA_SECTOR_COUNT = 32
SYSTEM_AREA_SIZE = 8_192
SYSTEM_AREA_END_LBA = 31

# Purpose unknown; do not describe this as metadata without further evidence.
UNKNOWN_REGION_START_LBA = 32
UNKNOWN_REGION_END_LBA = 7_839

DIRECTORY_START_LBA = 7_840
DIRECTORY_SECTOR_COUNT = 32
DIRECTORY_SIZE = 8_192
DIRECTORY_END_LBA = 7_871
DIRECTORY_ENTRY_SIZE = 32
DIRECTORY_ENTRY_COUNT = 256

# Observation from a reference image, not a verified allocation rule.
FIRST_OBSERVED_FILE_DATA_LBA = 7_904
# No purpose has been established for this gap in the observed layout.
POST_DIRECTORY_UNKNOWN_START_LBA = 7_872
POST_DIRECTORY_UNKNOWN_END_LBA = 7_903

DEFAULT_FILL_BYTE = 0xE5
UNUSED_DIRECTORY_USER = 0xE5
RECORD_PADDING_BYTE = 0x1A
# The reference HELLO.COM block is 0xE5 after its single 128-byte record.
ALLOCATION_SLACK_FILL_BYTE = 0xE5
SYSTEM_CONFIGURATION_TEXT = "A:8MB-HRD1"
SPLIT_SYSTEM_CONFIGURATION_TEXT = "A:5MB-HRD1"

# CP/M 2.2 Disk Parameter Block found in the bootable reference system area at
# byte offset 6401.  The complete byte sequence is intentionally not embedded.
# These mutually consistent fields independently derive the filesystem layout:
# OFF * SPT logical 128-byte records = DIRECTORY_START_LBA * 256 bytes.
DPB_REFERENCE_OFFSET = 6_401
DPB_SECTORS_PER_TRACK = 32  # 128-byte CP/M logical sectors/records
DPB_BLOCK_SHIFT = 5
DPB_BLOCK_MASK = 31
DPB_EXTENT_MASK = 1
DPB_MAXIMUM_BLOCK = 1_957
DPB_MAXIMUM_DIRECTORY_ENTRY = 255
DPB_ALLOCATION_RESERVED = (0xF0, 0x00)
DPB_DIRECTORY_CHECK_SIZE = 0
DPB_RESERVED_TRACKS = 490

# The two-filesystem ("split") format found in HD0_256_SPLIT.hda.  CP/M and
# CONFIG call the first and second filesystems HRD1 and HRD2 respectively; the
# command line deliberately calls them "low" and "high" to match that usage.
# OFF is an absolute track offset within the raw device, so the two allocation
# areas are contiguous even though their DSM values differ by two blocks.
SPLIT_LOW_DPB_MAXIMUM_BLOCK = 1_221
SPLIT_LOW_DPB_ALLOCATION_RESERVED = (0xC0, 0x00)
SPLIT_LOW_DPB_RESERVED_TRACKS = 2
SPLIT_HIGH_DPB_MAXIMUM_BLOCK = 1_223
SPLIT_HIGH_DPB_ALLOCATION_RESERVED = (0xC0, 0x00)
SPLIT_HIGH_DPB_RESERVED_TRACKS = 1_224

SPLIT_LOW_DIRECTORY_START_LBA = 32
SPLIT_LOW_DIRECTORY_END_LBA = 63
SPLIT_HIGH_DIRECTORY_START_LBA = 19_584
SPLIT_HIGH_DIRECTORY_END_LBA = 19_615
SPLIT_FIRST_USABLE_ALLOCATION_BLOCK = 2
SPLIT_LOW_FILESYSTEM_END_LBA = 19_583
SPLIT_HIGH_FILESYSTEM_END_LBA = 39_167

LOGICAL_RECORD_SIZE = 128
ALLOCATION_BLOCK_SIZE = LOGICAL_RECORD_SIZE << DPB_BLOCK_SHIFT  # 4 KiB
ALLOCATION_BLOCK_SECTORS = ALLOCATION_BLOCK_SIZE // SECTOR_SIZE
ALLOCATION_BLOCK_COUNT = DPB_MAXIMUM_BLOCK + 1
ALLOCATION_VALUE_SIZE = 2
ALLOCATION_VALUES_PER_ENTRY = 16 // ALLOCATION_VALUE_SIZE
RESERVED_ALLOCATION_BLOCKS = frozenset({0, 1, 2, 3})
FIRST_USABLE_ALLOCATION_BLOCK = 4
RECORDS_PER_ALLOCATION_BLOCK = ALLOCATION_BLOCK_SIZE // LOGICAL_RECORD_SIZE
LOGICAL_EXTENT_RECORDS = 128
DIRECTORY_EXTENT_RECORDS = LOGICAL_EXTENT_RECORDS * (DPB_EXTENT_MASK + 1)
DIRECTORY_EXTENT_SIZE = DIRECTORY_EXTENT_RECORDS * LOGICAL_RECORD_SIZE
FILESYSTEM_END_LBA = (
    DIRECTORY_START_LBA + ALLOCATION_BLOCK_COUNT * ALLOCATION_BLOCK_SECTORS - 1
)

assert IMAGE_SIZE == SECTOR_SIZE * SECTOR_COUNT
assert SYSTEM_AREA_SIZE == SECTOR_SIZE * SYSTEM_AREA_SECTOR_COUNT
assert DIRECTORY_SIZE == SECTOR_SIZE * DIRECTORY_SECTOR_COUNT
assert DIRECTORY_ENTRY_COUNT == DIRECTORY_SIZE // DIRECTORY_ENTRY_SIZE
assert DIRECTORY_START_LBA == (
    DPB_RESERVED_TRACKS * DPB_SECTORS_PER_TRACK * LOGICAL_RECORD_SIZE // SECTOR_SIZE
)
assert ALLOCATION_BLOCK_SIZE == 4_096
assert ALLOCATION_BLOCK_SECTORS == 16
assert DIRECTORY_EXTENT_SIZE == 32_768
