	.Z80
	TITLE UTILITY TABLES AND MESSAGES
	SUBTTL FLOPPY CONVERSION TABLES
;
	.SALL
DEFT	MACRO STRING1
	LOCAL	DEFT1
	DEFB	DEFT1-$-1
	DEFB	STRING1
DEFT1:
	ENDM
;
ESC	EQU	1BH
CRLF	EQU	0A0DH
;
TABLES:
	INCLUDE UTTAB.MAC	;GET TABLES
	REPT	TABLE'Sorry , not yet implemented ... '
	DEFT	'DISK NOT READY'	;2A
	DEFT	'Press any key to return to main menu'		;2B
	DEFT	'Press any key when ready'	;2C
	DEFT	'stopped from keyboard';2D
	DEFT	'to escape enter <ESC> OR <0>' ;2E
	DEFÔ	'0PP2000Ã UTILITÙ PRS+400H-$	;TABLE RESERVE
	DEFB	0FFH
	ENDM
;
;=============================================
;THIS FILE STORES THE CONFIGURATION OF THE
;P2000C FORMAT AND COPY UTILITY 0PROGRAM
;
;BYTES 0 TO 7: FLOPPY DRIVE DESCRIPTORS
;EACH FLOPPY UNIT HAS A 2-BYTE OGRAÍ  Relº 1.2   84.02.030@§ ;2F
	DEFT	'SELECT:' 
	DEFT	'FORMAT FLOPPY DISK'
	DEFT	'FORMAT HARD DISK'
	DEFT	'COPY FLOPPY DISK'
	DEFT	'REDEFINE LANGUAGE/FLOPPY DISK ARRANGEMENT'
	DEFB	0,0,0		;35,37
	DEFT	'Enter SOURCE drive (1 to 4)      : ' ;38
	DESCRIPTOR
;THE FIRST IS	81H IF SINGLE SIDED AND
;		82H IF DOUBLE SIDED
;THE SECOND IS THE NUMBER OF TRACKS
;
;BYTE 8: NUMBER OF LANGUAGES STORED (N)
;BYTE 9: ACTUAL LANGUAGE NUMBER (0 TO N-1) 
;
;BYTE A AND B: LENGTH OF FIRST LANGUAGE BLOCK
;====DEFT	'Enter DESTINATION drive (1 to 4) : ' ;39
	DEFT	'Do you wish to verify while copying '		;3A
	DEFT	'0PCOPY FLOPPY DISK TO P2000C FORMAT0@§ ;3B
	DEFT	'Illegal DESTINATION disk ! '
	DEFT	'Select SOURCE disk type : '	;3D
	DEFT	'Which SYSTEM?'			;3E=========================================
;
	DEFB	0FFH,28H
	DEFB	0FFH,28H
	DEFB	0FFH,28H
	DEFB	0FFH,28H
;
	DEFB	2	;DEFINE TWO LANGUAGE
;
UKST:	DEFW	UKEND-UKST
	DEFB	'English         ' ;16 BYTES!
YN:	DEFB	'YN'
;
;THIS IS THE ACTUAL TEXT BLOCK F
	DEFT	'Next copy'			;3F
	DEFT	'WARNING : Destination disk will be DELETED!';40
	DEFT	'0PFORMAT HARD DISK0@'	;41
	DEFT	'Hard disk NOT READY'		;42
	DEFT	'Which DRIVE (1 or 2)?'		;43
XUK44:	DEFB	XUK45-XUK44-1
	DEFB 'Please ensure that the hard disk OR ENGLISH
UK0:	DEFB	0,0
XUK2:	DEFB	XUK3-XUK2-1
	DEFB	ESC,'03'
	DEFB	'DISK ERROR'
	DEFB	ESC,'0',40H
XUK3:	DEFB	0
	DEF×	0,0,0,0,0,0
XUK10:	DEFB	XUK11-XUK10-1
	DEFB 'Enter (sequentially) the DRIVE NUMBER(S) containing the disks'
	DEFW CRLF
	DEFB 'is set up for 256 byte sectors'
	DEFW	CRLF
	DEFB	'WARNING : any data on the disk will be deleted!'
	DEFW	CRLF
	DEFB	'Have you made a backup of your hard disk? If ready, type YES'
XUK45:	DEFT	'YES'				;45
	DEFT	'Number of BAD TRACKs:'		;46
XUK47:	DEFto be formatted, terminate with <CR>'
	DEFW CRLF
	DEFB 'Exit with <ESC> or <0>'
	DEFW CRLF
	DEFB 'Formatting continues cyclically until an empty drive is found'
	DEFW CRLF,CRLF
	DEFB 'Drive(s) to format (1 to 4) : '
XUK11:	DEFB XUK12-XUK11-1
	DEFB B	XUK48-XUK47-1,'Your hard disk is being FORMATTED',0DH,0AH
	DEFB	'This process takes some time, please WAIT ...'
XUK48:	DEFT	'Verifying hard disk format'
	DEFT	'Actual hard disk capacity in KBYTES:' ;49
	DEFB	0,0,0,0,0,0		;4A-4F
	DEFB	0,0,0,0,0			;50'Insert disk(s) - NOTE: Any data on the disks will be destroyed'
XUK12:	DEFB	XUK13-XUK12-1
	DEFW	CRLF
	DEFB	'to return to CP/M you need a system disk in A:'
	DEFB	' then enter any key'
XUK13:	DEFT	'DRIVE -'
	DEFT	'   TRACK -'
	DEFT	'(y/n) ? '		;15
-54
	DEFÔ	'0PSELECT LANGUAGE AND FLOPPY DISK ARRANGEMENT0@';55
XUK56:	DEFB	XUK57-XUK56-1
	DEFB 'During this operation, the disk from which the UTIL program was'
	DEFW	CRLF
	DEFB 'executed must remain in its drive until the MAIN MENU is displayed'
		DEFÔ	'0PFORMAT FLOPPY DISK TO P2000C FORMAT0@§ ;16
	DEFT	'Press any key when ready'	;17
	DEFT	'DISK OPERATION , please wait ! ' ;18
	DEFT	'Ready:'		;19
	DEFT	'Disk is full'		;1A
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0 ;1B-27
	DEFT	'   SIDE -'		;28
	DEFT	DEFW	CRLF
XUK57:	DEFB	XUK58-XUK57-1
	DEFB	'Define your FLOPPY DISK arrangement by typing the'
	DEFW	CRLF
	DEFB	'appropriate number against each drive : '
	DEFW	CRLF
	DEFB	'1 - 160 kbytes',0DH,0AH
	DEFB	'2 - 640 kbytes',0DH,0AH
	DEFB	'3 - Not existing'
XUK58:	DEFB	XUK59-XUK58-1
	DEFB	'Select language by typing the associated number'
	DEFW	CRLF
	DEFB	'All other keys accept the current language'
XUK59:	DEFT	'Do you wish to KEEP the other languages? '
	DEFT	'5A'
	DEFT	'Copied files:'	;5B
	DEFT	'0C FORMAT0@§ ;3B
	DEFT	'Illegale disk Kombination ! '	;3C
	DEFT	'Typ der QUELLENDISKETTE : '	;3D
	DEFT	'Welches SYSTEM?'		;3E
	DEFT	'Nexte Kopie'			;3F
	DEFT	'WARNUNG : Zieldiskette wird GEL\SCHT!';40
	DEFT	'0PHARD DISK FORMATIEREN0@'	;41
	DEFT	'5C'
	DEFT	'5D'
	DEFT	'5E'
	DEFT	'5F'
	DEFT	'60'





UKEND:
	DEFW	DAEND-UKEND
	DEFB	'Deutsch         ' ;16 BYTES!
	DEFB	'JN'		;YES AND NO
;
;THIS IS THE ACTUAL TEXT BLOCK FOR DEUTSCH/AUSTRIAN
DA0:	DEFB	0,0
XDA2:	DEFB	XDA3-XDA2-1
	DEFB	ESCHard disk NICHT BEREIT'	;42
	DEFT	'Welches LAUFWERK (1 oder 2)?'	;43
XDA44:	DEFB	XDA45-XDA44-1
	DEFB	'Bitte }berpr}fen ob das Laufwerk 256 Bytes Sektorgr|~e hat!'
	DEFW	CRLF
	DEFB	'WARNUNG : alle Daten auf der Disk werden gel|scht!'
	DEFW	CRLF
	DEFB,'03'
	DEFB	'DISK FEHLER'
	DEFB	ESC,'0',40H
XDA3:	DEFB	0
	DEF×	0,0,0,0,0,0
XDA10:	DEFB	XDA11-XDA10-1
	DEFB	'LAUFWERKNUMMER f}r Formatierung sequentiell eingeben'
	DEF×	CRLF
	DEFÂ	'Eingabe mit RET beenden, aussteigen mit ESC oder 0'
 	DEF×	CRLF
	D	'Haben Sie Ihre Files gerettet? Wenn bereit, JA tippen:'
XDA45:	DEFT	'JA'				;45
	DEFT	'Anzahl der KAPUTTEN SPUREN:'		;46
XDA47:	DEFB	XDA48-XDA47-1,'Ihre Harddisk wird FORMATIERT',0DH,0AH
	DEFB	'Dieser Vorgang dauert einige Zeit, bitte WARTEN ...'
XDEFB	'Bei MEHREREN Eingaben wird es '
	DEFB	' ABW[CHSLEND formatiert'
	DEFW	CRLF,CRLF
	DEFB	'Laufwerke zu formatieren: (1 TO 4):'
XDA11:	DEFT	'Disketten(n) einlegen, VORSICHT, Daten werden ZERST\RT!'
XDA12:	DEFB	XDA13-XDA12-1
	DEFB 'F}r die R}ckkehr iA48:	DEFT	'Harddisk Format wird verifiziert'
	DEFT	'Aktuelle Harddiskkapazit{t in KBYTES:' ;49
	DEFB	0,0,0,0,0,0		;4A-4F
	DEFB	0,0,0,0,0			;50-54
	DEFÔ	'0PSPRACHE UND FLOPPY KONFIGURATION DEFINIEREN0@';55
XDA56:	DEFB	XDA57-XDA56-1
	DEFB 'Die Disketns CP/M ist eine SYSTEM DISKETTE notwendig'
	DEFB    0DH,0AH,'in DRIVE-A und eine Taste dr}cken!'
XDA13:	DEFT	'LAUFWERK -'
	DEFT	'   SPUR -'
	DEFT	'(J/N) ? '		;15
	DEFÔ	'0PFLOPPY FORMATIEREN ZUM P2000C FORMAT0@§ ;16
	DEFT	'Wenn bereit, eine Taste dte mit dem UTIL Program mu~ w{hrend dieser Operation'
	DEFW	CRLF
	DEFB 'in ihrem Laufwerk bleiben bis das HAUPTMEN] erscheint!'
	DEFW	CRLF
XDA57:	DEFB	XDA58-XDA57-1
	DEFB	'FLOPPY DISK Konfiguration definieren'
	DEFW	CRLF
	DEFB	'f}r alle Laufwerke mir}cken'	;17
	DEFT	'DISK OPERATION, bitte warten!' ;18
	DEFT	'Fertig:'		;19
	DEFT	'Disk ist voll'		;1A
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0 ;1B-27
	DEFT	'   SEITE -'		;28
	DEFB	0
	DEFT	'DISK NICHT BEREIT'	;2A
	DEFT	'EINE TASTE DR]CKEN'	;2B
	DEFT	'Eine Tt der entsprechenden Nummer : '
	DEFW	CRLF
	DEFB	'1 - 160 kbytes',0DH,0AH
	DEFB	'2 - 640 kbytes',0DH,0AH
	DEFB	'3 - Nicht vorhanden'
XDA58:	DEFB	XDA59-XDA58-1
	DEFB	'W{hlen Sie die Sprache mit der entsprechenden Nummer,'
	DEFW	CRLF
	DEFB	'alle andeaste dr}cken wenn bereit'	;2C
	DEFT	'GESTOPPT VON TASTATUR';2D
	DEFT	'AUSSTEIGEN MIT "ESC" ODER "0"' ;2E
	DEFÔ	'0PP2000Ã UTILITÙ PROGRAÍ  Versº 1.2   84.02.030@§ ;2F
	DEFT	'W[HLEN:' 
	DEFT	'FLOPPY FORMATIEREN'
	DEFT	'HARD DISK FORMATIEREN'
	DEFT	're Tasten lassen Deutsch gelten'
XDA59:	DEFT	'Wollen Sie die anderen Sprachen BEHALTEN? '
	DEFT	'5A'
	DEFT	'Kopierte Files:'	;5B
	DEFT	'5C'
	DEFT	'5D'
	DEFT	'5E'
	DEFT	'5F'
	DEFT	'60'
DAEND:
	END
FLOPPY DISK KOPIEREN'
	DEFT	'SPRACHE UND FLOPPY KONFIGURATION DEFINIEREN' ;34
	DEFB	0,0,0		;35,37
	DEFT	'Kopieren VON Drive (1-4):     ' ;38
	DEFT	'ZU Drive (1-4):               ' ;39
	DEFT	'VERIFIZIEREN?'		;3A
	DEFT	'0PFLOPPY DISK KOPIEREN ZUM P200